name: MasterDeployCI
on:
  push:
    branches:
      - report_generator

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Setup environment
      run: |
        echo MIXPANEL_TOKEN=${{ secrets.MIXPANEL_TOKEN }} >> .env
    - name: Build project
      run: npm run build
    # - name: Run Tests
    #   run: export CI=true && npm run test -- --coverage
    - name: Deploy to GH pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
        BASE_BRANCH: report_generator # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
